---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
Debug:
  friendly_error_httpcode: true
Upload_Validator:
  default_max_file_size:
    '[image]': '4m'
    '[doc]': '5m'
    'jpeg': 4000
